name: Test

on: [push, pull_request]

jobs:
  ci:
    name: Test all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        combo: [
          { rust: stable, flags: --all-features },
          { rust: 1.70.0, flags: --all-features },
          { rust: stable, flags: --features=default },
          { rust: 1.46.0, flags: --features=default },
          { rust: stable, flags: --no-default-features },
          { rust: 1.46.0, flags: --no-default-features },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.combo.rust }}
          components: rustfmt, clippy
      - name: Build
        run: cargo build --all-targets ${{ matrix.combo.flags }}
      - name: Test
        run: cargo test ${{ matrix.combo.flags }}
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets ${{ matrix.combo.flags }} -- -D warnings
